# configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: dpmconfig
  annotations:
    user: wangchunyan
    purpose: monitor
  namespace: docker-monitor
data:
  metrics.json: "{\"docker\":{\"daemonSock\":\"unix:///tmp/run/docker.sock\",\"apiVersion\":\"1.37\",\"procDir\":\"/tmp/hostproc\"},\"monitor\":{\"items\":[\"cpu\",\"memory\"],\"frequency\":1},\"listen\":{\"addr\":\"\",\"port\":3280,\"wanName\":\"ens33\"},\"consulRegister\":{\"addr\":\"http://172.16.13.129:8500,http://172.16.13.130:8500,http://172.16.13.131:8500\",\"dc\":\"dc1\",\"serviceName\":\"dpm\"}}"
